---
- hosts: home:work

  vars:
    - download_dir: "/tmp"

  tasks:
    - name: "Update all packages to the latest version"
      become: yes
      apt:
        upgrade: dist

    - name: "Install all packages and dependencies"
      become: yes
      apt:
        name:
          - chromium
          - libffi-dev
          - python
          - python3
          - python-pip
          - python3-pip
        state: latest

    - name: "Update pip2"
      command: "pip2 install -U --user pip"
      register: pip2_result
      changed_when: "'already up-to-date' not in pip2_result.stdout"

    - name: "Update pip3"
      command: "pip3 install -U --user pip"
      register: pip3_result
      changed_when: "'already up-to-date' not in pip3_result.stdout"

    - name: "Download Sublime Text 3"
      get_url:
        url: https://download.sublimetext.com/sublime-text_build-3126_amd64.deb
        dest: "{{ download_dir }}/sublime-text_build-3126_amd64.deb"

    - name: "Install Sublime Text 3"
      become: yes
      apt:
        deb: "{{ download_dir }}/sublime-text_build-3126_amd64.deb"

    - name: "Ensure that ~/.local/bin is in PATH"
      lineinfile:
        dest: "$HOME/.zshrc"
        line: "export PATH=$HOME/.local/bin:$PATH"
