---
- hosts: all

  tasks:
    - include_vars: vars.yml

    - name: "Add user to additional groups"
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        groups: "{{ item }}"
        append: yes
      with_items:
        - docker

    - name: "Set zsh as default shell"
      become: yes
      command: chsh -s /bin/zsh
      changed_when: false
