---
- hosts: all

  tasks:
    - name: "Install apt dependencies"
      become: yes
      tags:
        - install
      apt:
        state: latest
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common

    - name: "Add keys for additional apt repositories"
      become: yes
      tags:
        - install
      apt_key:
        state: present
        url: "{{ item.url }}"
        id: "{{ item.id }}"
      with_items:
        - { url: "https://yum.dockerproject.org/gpg", id: "58118E89F3A912897C070ADBF76221572C52609D" }

    - name: "Add additional apt repositories"
      become: yes
      tags:
        - install
      apt_repository:
        state: present
        repo: "{{ item }}"
      with_items:
        - "deb https://apt.dockerproject.org/repo/ {{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }} main"

    - name: "Install packages"
      become: yes
      tags:
        - install
      apt:
        state: latest
        name:
          - chromium
          - curl
          - docker-engine
          - libcanberra-gtk-module  # PyCharm dep
          - python-pip
          - python3
          - python3-pip
          - vim
          - wget
          - zsh

    - name: "Download Sublime Text 3"
      tags:
        - install
      get_url:
        url: https://download.sublimetext.com/sublime-text_build-3126_amd64.deb
        dest: /tmp/sublime-text-3.deb

    - name: "Install Sublime Text 3"
      become: yes
      tags:
        - install
      apt:
        deb: /tmp/sublime-text-3.deb
