---
- hosts: all

  vars:
    sys_dl_dir: "/tmp"
    sys_deb_downloads:
      - { url: "https://download.sublimetext.com/sublime-text_build-3126_amd64.deb",
          dest: "{{ sys_dl_dir }}/sublime.deb" }


  tasks:
    - name: "Start package downloads"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      async: 300
      poll: 0
      register: dl_job
      with_items: "{{ sys_deb_downloads }}"

    - name: "Install apt dependencies"
      become: yes
      apt:
        state: latest
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common

    - name: "Add keys for additional apt repositories"
      become: yes
      apt_key:
        state: present
        url: "{{ item.url }}"
        id: "{{ item.id }}"
      with_items:
        - { url: "https://yum.dockerproject.org/gpg", id: "58118E89F3A912897C070ADBF76221572C52609D" }

    - name: "Add additional apt repositories"
      become: yes
      apt_repository:
        state: present
        repo: "{{ item }}"
      with_items:
        - "deb https://apt.dockerproject.org/repo/ {{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }} main"

    - name: "Install packages"
      become: yes
      apt:
        state: latest
        name:
          - build-essential
          - chromium
          - curl
          - docker-engine
          - libbz2-dev
          - libcanberra-gtk-module  # PyCharm dep
          - libncurses5-dev
          - libncursesw5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - llvm
          - make
          - python
          - python-pip
          - python3
          - python3-pip
          - vim
          - wget
          - xz-utils
          - zlib1g-dev
          - zsh

    - name: 'Wait for downloads to complete'
      async_status: jid={{ item.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 300
      with_items: "{{ dl_job.results }}"

    - name: "Install downloaded packages"
      become: yes
      apt:
        deb: "{{ item.dest }}"
      with_items: "{{ sys_deb_downloads }}"
