---
- hosts: all

  tasks:
    - include_vars: vars.yml

    - name: "Update .zshrc"
      template:
        src: .zshrc.j2
        dest: "{{ ansible_user_dir }}/.zshrc"
        backup: yes

    - name: "Update .aliases"
      template:
        src: .aliases.j2
        dest: "{{ ansible_user_dir }}/.aliases"
        backup: yes

    - name: "Update .gitconfig"
      template:
        src: .gitconfig.j2
        dest: "{{ ansible_user_dir }}/.gitconfig"
        backup: yes

    - name: "Set default python versions"
      template:
        src: pyenv/.version.j2
        dest: "{{ ansible_user_dir }}/.pyenv/.version"
        backup: yes
