---
- hosts: all

  tasks:
    - include_vars: vars.yml

    - name: "Clone Oh My Zsh"
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"
        depth: 1

    - name: "Clone pyenv"
      git:
        repo: https://github.com/yyuu/pyenv.git
        dest: "{{ ansible_user_dir }}/.pyenv"
        depth: 1

    - name: "Clone pyenv-virtualenv"
      git:
        repo: https://github.com/yyuu/pyenv-virtualenv.git
        dest: "{{ ansible_user_dir }}/.pyenv/plugins/pyenv-virtualenv"
        depth: 1

    - name: "Install Python"
      command: "{{ ansible_user_dir }}/.pyenv/bin/pyenv install {{ item }}"
      environment:
        PYENV_ROOT: "{{ ansible_user_dir }}/.pyenv"
      register: result
      changed_when: "'Installed Python' in result.stdout"
      failed_when: "'already exists' not in result.stderr and result.rc != 0"
      with_items: "{{ py_versions }}"

    - name: "Install pip packages"
      pip:
        executable: "{{ item.key }}"
        extra_args: --user
        name: "{{ item.value }}"
        state: latest
      environment:
        PATH: "{{ ansible_user_dir }}/.local/bin:/usr/bin"
      with_dict: "{{ pip_pkgs }}"
